version: "3.5"

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./docker/postgres/.env

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn project.wsgi -b 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./docker/app/.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
       - "8080:80"
    depends_on:
      - app


volumes:
  postgres-data:
