version: "3.5"

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./docker/postgres/.env

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./docker/app/.env
    depends_on:
      - db

volumes:
  postgres-data: